import type { ModelSummary, PredictionResponse, ResultsSummaryResponse } from './types';

export const modelMetrics: ModelSummary[] = [
  {
    model_name: 'SoilAI EfficientNetV2L',
    family: 'efficientnetv2l',
    hamming_accuracy: 0.911504424778761,
    macro_f1_global: 0.903,
    per_label_accuracy: {
      K0: 0.8938,
      K1: 0.8673,
      K2: 0.9027,
      N0: 0.9292,
      N1: 0.9646,
      N2: 0.9292,
      P0: 0.9027,
      P1: 0.9027,
    },
    thresholds: {
      K0: 0.64,
      K1: 0.64,
      K2: 0.74,
      N0: 0.24,
      N1: 0.76,
      N2: 0.82,
      P0: 0.62,
      P1: 0.18,
    },
    sources: { results_valid: '/npk_models_efficientnetv2l/results_valid.json' },
  },
  {
    model_name: 'SoilAI DenseNet201',
    family: 'densenet201',
    hamming_accuracy: 0.8982300884955752,
    macro_f1_global: 0.889,
    per_label_accuracy: {
      K0: 0.9115,
      K1: 0.8496,
      K2: 0.9027,
      N0: 0.9027,
      N1: 0.9558,
      N2: 0.8938,
      P0: 0.885,
      P1: 0.885,
    },
    thresholds: {
      K0: 0.48,
      K1: 0.72,
      K2: 0.82,
      N0: 0.34,
      N1: 0.88,
      N2: 0.70,
      P0: 0.32,
      P1: 0.44,
    },
    sources: { results_valid: '/npk_models_densenet201/results_valid.json' },
  },
  {
    model_name: 'SoilAI MobileNetV2',
    family: 'mobilenetv2',
    hamming_accuracy: 0.8584070796460177,
    macro_f1_global: 0.844,
    per_label_accuracy: {
      K0: 0.823,
      K1: 0.8407,
      K2: 0.8761,
      N0: 0.885,
      N1: 0.9204,
      N2: 0.8938,
      P0: 0.8142,
      P1: 0.8142,
    },
    thresholds: {
      K0: 0.44,
      K1: 0.8,
      K2: 0.24,
      N0: 0.74,
      N1: 0.74,
      N2: 0.22,
      P0: 0.58,
      P1: 0.24,
    },
    sources: { results_valid: '/npk_models_mobilenetv2/results_valid.json' },
  },
];

export const resultsSummary: ResultsSummaryResponse = {
  best_model: modelMetrics[0],
  models: modelMetrics,
  baseline_notes: [
    'Le meilleur modèle est retenu sur le hamming accuracy validé par les artefacts du projet.',
    'La plateforme ne remplace pas le laboratoire: elle fournit un pré-diagnostic rapide et une aide à la décision.',
    'EfficientNetV2L est mis en avant comme modèle de référence; DenseNet201 reste un comparateur scientifique solide.',
  ],
};

export const samplePrediction: PredictionResponse = {
  model_name: 'SoilAI EfficientNetV2L',
  prediction: { K_level: 'K1', N_level: 'N1', P_level: 'P0' },
  confidence: 0.91,
  status: 'ok',
  can_trust_result: true,
  quality_check: {
    valid: true,
    status: 'ok',
    width: 1024,
    height: 768,
    brightness: 112.4,
    contrast: 31.2,
    sharpness: 18.7,
    issues: [],
  },
  confidence_details: {
    max_prob: 0.91,
    second_prob: 0.08,
    margin: 0.83,
    top_label: 'N1',
    top_group: 'N',
  },
  interpretation: 'Estimation indicative du profil nutritif du sol. Signal suffisamment fort pour orienter l’action.',
  recommendation: 'Surveillance recommandée, confirmation laboratoire conseillée avant décision finale.',
  agronomic_advice: {
    potassium: {
      nutrient: 'K',
      level: 'K1',
      priority: 'moderate',
      advice: 'Classe intermédiaire: suivre le potassium et confirmer si la parcelle sert à une décision sensible.',
      soil_status: 'niveau intermédiaire',
      summary: 'Potassium à suivre avec prudence.',
      warning: 'Conseil indicatif fondé sur une classe prédite à partir d’une image. Il ne fournit ni dose exacte ni recommandation de fertilisation: une analyse de laboratoire et un avis agronomique restent nécessaires avant toute décision.',
    },
    nitrogen: {
      nutrient: 'N',
      level: 'N1',
      priority: 'moderate',
      advice: 'Classe intermédiaire: surveiller l’azote et compléter par une analyse si le pilotage doit être précis.',
      soil_status: 'niveau intermédiaire',
      summary: 'Azote à suivre avec prudence.',
      warning: 'Conseil indicatif fondé sur une classe prédite à partir d’une image. Il ne fournit ni dose exacte ni recommandation de fertilisation: une analyse de laboratoire et un avis agronomique restent nécessaires avant toute décision.',
    },
    phosphorus: {
      nutrient: 'P',
      level: 'P0',
      priority: 'high',
      advice: 'Classe faible: contrôler le phosphore en priorité et confirmer avant toute correction.',
      soil_status: 'niveau faible',
      summary: 'Phosphore à surveiller en priorité.',
      warning: 'Conseil indicatif fondé sur une classe prédite à partir d’une image. Il ne fournit ni dose exacte ni recommandation de fertilisation: une analyse de laboratoire et un avis agronomique restent nécessaires avant toute décision.',
    },
    global_advice: {
      soil_score: 52,
      soil_level: 'à surveiller',
      soil_status: 'surveillance prioritaire',
      priority_focus: 'P',
      priority_summary: 'Priorité principale sur P (P0).',
      summary: 'Score global 52/100 (à surveiller). Priorité principale sur P (P0). Les autres nutriments suivent une logique de priorité moderate et moderate.',
      warning: 'Conseil indicatif fondé sur une classe prédite à partir d’une image. Il ne fournit ni dose exacte ni recommandation de fertilisation: une analyse de laboratoire et un avis agronomique restent nécessaires avant toute décision.',
    },
  },
  warning_message: 'Résultat exploitable pour un pré-diagnostic indicatif.',
  recommendation_message: 'Résultat jugé suffisamment robuste pour un pré-diagnostic indicatif.',
  is_mock: true,
  timestamp: new Date().toISOString(),
  source: 'mock-sample',
  model_status: 'mock',
  probabilities: { K1: 0.87, N1: 0.91, P0: 0.88 },
};

export const parcelHistory = [
  { parcel: 'Parcelle A12', crop: 'Maïs', status: 'Stable', confidence: 0.91, k: 'K1', n: 'N1', p: 'P0', date: 'Aujourd’hui', priorityFocus: 'P', soilScore: 74, soilLevel: 'moyen' },
  { parcel: 'Parcelle B07', crop: 'Tomate', status: 'À confirmer', confidence: 0.76, k: 'K2', n: 'N1', p: 'P1', date: 'Hier', priorityFocus: 'K', soilScore: 56, soilLevel: 'à surveiller' },
  { parcel: 'Parcelle C03', crop: 'Riz', status: 'Surveillance', confidence: 0.84, k: 'K0', n: 'N2', p: 'P0', date: 'Il y a 3 jours', priorityFocus: 'N', soilScore: 38, soilLevel: 'critique' },
];
